feat: add laura-rocha profile
digitalinnovationone/dio-lab-open-source pull request #8906
Opened 2023-09-01 14:15 UTC by laura-rocha

**Descrição**

Adiciona Profile README da conta laura-rocha.

**Tipo de alteração**

- [x] Resolução do Desafio Profile README
- [ ] Correção de bug
- [ ] Nova funcionalidade
- [ ] Alteração na documentação
- [ ] Outro (especifique)

**Checklist**

- [x] Minhas alterações não deletam partes do projeto
- [x] Minhas alterações não introduzem novos problemas
- [x] Minha contribuição está de acordo com o [Guia de Contribuição](https://github.com/elidianaandrade/dio-lab-open-source/blob/main/CONTRIBUTING.md)

**Comentários adicionais**

N/A.

2023-10-16 00:54 UTC, falvojr requested changes

2023-10-16 00:54 UTC, falvojr commented on community/image.png
@laura-rocha o ideal é não subir as imagens neste repositório, pode usar imagens externas, sem problemas 👊😉 ALém disso, ela não está sendo usada no seu arquivo .md. Sendo assim, poderia removê-la e atualizar esse PR, por favor? Abraço!

2023-10-16 22:56 UTC, merged

2023-10-16 22:59 UTC, laura-rocha commented on community/image.png
Muito obrigada pelo aviso, Venilton. Eu ia tentar colocar aquela imagem no meu perfil, acabei desistindo e esqueci de excluir. Mais uma vez agradeço!

2023-10-16 23:00 UTC, laura-rocha commented on community/image.png
Você poderia confirmar se eu fiz a correção corretamente, por favor?

2023-10-17 01:31 UTC, falvojr commented on community/image.png
Tudo certo @laura-rocha, nossa automação já validou e fez o merge! Muitíssimo obrigado pela colaboração 👊☺️